# Generated by Django 4.2.2 on 2023-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'İletişim formu Ayarları',
                'verbose_name_plural': 'İletişim Formları',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('file_upload', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Hizmetlerimiz Bölümü Ayarları',
                'verbose_name_plural': 'Hizmetlerimiz Bölümü Formu',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Ürünlerimiz Bölümü Ayarları',
                'verbose_name_plural': 'Ürünlerimiz Bölümü Formu',
            },
        ),
    ]
