# Generated by Django 4.2.3 on 2023-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='file_upload',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
